[2024-06-11T21:29:30.670+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:29:30.736+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701227 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:29:30.765+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701227 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:29:30.766+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:29:30.804+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701227> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:29:30.815+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701227', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmpn2tpzxd7']
[2024-06-11T21:29:30.818+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=286) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:29:30.819+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask load_index_id_701227
[2024-06-11T21:29:30.820+0000] {standard_task_runner.py:63} INFO - Started process 287 to run task
[2024-06-11T21:29:30.913+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701227 scheduled__2024-06-10T00:00:00+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:29:31.117+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701227' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:29:31.119+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:29:31.178+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:29:31.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:29:31.180+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:29:31.192+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701227, execution_date=20240610T000000, start_date=20240611T212930, end_date=20240611T212931
[2024-06-11T21:29:31.212+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 145 for task load_index_id_701227 (Task failed due to SystemExit(1); 287)
[2024-06-11T21:29:31.236+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:29:31.263+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:29:31.267+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T21:31:32.985+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:31:33.041+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701227 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:31:33.067+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701227 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:31:33.069+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:31:33.112+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701227> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:31:33.124+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701227', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp4_wd8xzp']
[2024-06-11T21:31:33.126+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=427) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:31:33.128+0000] {standard_task_runner.py:91} INFO - Job 195: Subtask load_index_id_701227
[2024-06-11T21:31:33.128+0000] {standard_task_runner.py:63} INFO - Started process 430 to run task
[2024-06-11T21:31:33.229+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701227 scheduled__2024-06-10T00:00:00+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:31:33.412+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701227' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:31:33.414+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:31:33.479+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:31:33.481+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:31:33.483+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:31:33.496+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701227, execution_date=20240610T000000, start_date=20240611T213133, end_date=20240611T213133
[2024-06-11T21:31:33.523+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 195 for task load_index_id_701227 (Task failed due to SystemExit(1); 430)
[2024-06-11T21:31:33.547+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:31:33.591+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:31:33.600+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T21:41:38.243+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:41:38.291+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701227 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:41:38.313+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701227 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:41:38.314+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:41:38.343+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701227> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:41:38.356+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701227', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmp6_v5yp0s']
[2024-06-11T21:41:38.360+0000] {standard_task_runner.py:91} INFO - Job 252: Subtask load_index_id_701227
[2024-06-11T21:41:38.363+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=240) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:41:38.365+0000] {standard_task_runner.py:63} INFO - Started process 241 to run task
[2024-06-11T21:41:38.432+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701227 scheduled__2024-06-10T00:00:00+00:00 [running]> on host 8195540d7f15
[2024-06-11T21:41:38.588+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701227' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:41:38.590+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:41:38.670+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:41:38.671+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data.py", line 19, in load_index
    print(response.json()["info"])
          ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'info'
[2024-06-11T21:41:38.687+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701227, execution_date=20240610T000000, start_date=20240611T214138, end_date=20240611T214138
[2024-06-11T21:41:38.704+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 252 for task load_index_id_701227 ('info'; 241)
[2024-06-11T21:41:38.742+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:41:38.786+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:41:38.793+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
