[2024-06-07T09:20:21.937+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T09:20:22.006+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_702974 manual__2024-06-07T09:17:57.181605+00:00 [queued]>
[2024-06-07T09:20:22.024+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_702974 manual__2024-06-07T09:17:57.181605+00:00 [queued]>
[2024-06-07T09:20:22.026+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-07T09:20:22.053+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_702974> on 2024-06-07 09:17:57.181605+00:00
[2024-06-07T09:20:22.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_702974', 'manual__2024-06-07T09:17:57.181605+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmpl4uqb31b']
[2024-06-07T09:20:22.071+0000] {standard_task_runner.py:91} INFO - Job 104: Subtask load_index_id_702974
[2024-06-07T09:20:22.074+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=280) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-07T09:20:22.076+0000] {standard_task_runner.py:63} INFO - Started process 281 to run task
[2024-06-07T09:20:22.144+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_702974 manual__2024-06-07T09:17:57.181605+00:00 [running]> on host e6f094d2943c
[2024-06-07T09:20:22.424+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_702974' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T09:17:57.181605+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-07T09:17:57.181605+00:00'
[2024-06-07T09:20:22.426+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T10:43:43.529+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-07T10:43:43.593+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-07T10:43:43.632+0000] {process_utils.py:132} INFO - Sending 15 to group 281. PIDs of all processes in the group: [281]
[2024-06-07T10:43:43.636+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 281
[2024-06-07T10:43:43.663+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-07T10:43:43.777+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T10:43:44.215+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=281, status='terminated', exitcode=0, started='09:20:21') (281) terminated with exit code 0
