[2024-06-11T21:29:10.641+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:29:10.790+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:29:10.806+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:29:10.931+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:29:11.024+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_19722414> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:29:11.070+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_19722414', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp36xe3gcw']
[2024-06-11T21:29:11.089+0000] {standard_task_runner.py:91} INFO - Job 138: Subtask load_index_id_19722414
[2024-06-11T21:29:11.085+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:29:11.097+0000] {standard_task_runner.py:63} INFO - Started process 262 to run task
[2024-06-11T21:29:11.344+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:29:12.106+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_19722414' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:29:12.113+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:29:13.040+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:29:13.062+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:29:13.065+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:29:13.168+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_19722414, execution_date=20240610T000000, start_date=20240611T212910, end_date=20240611T212913
[2024-06-11T21:29:13.240+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 138 for task load_index_id_19722414 (Task failed due to SystemExit(1); 262)
[2024-06-11T21:29:13.309+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:29:13.412+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:29:13.432+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T21:30:31.901+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:30:31.961+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:30:31.978+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:30:31.979+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:30:32.010+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_19722414> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:30:32.025+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=372) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:30:32.027+0000] {standard_task_runner.py:63} INFO - Started process 373 to run task
[2024-06-11T21:30:32.025+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_19722414', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp0g2ebfim']
[2024-06-11T21:30:32.029+0000] {standard_task_runner.py:91} INFO - Job 177: Subtask load_index_id_19722414
[2024-06-11T21:30:32.123+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:30:32.375+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_19722414' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:30:32.376+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:30:32.450+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:30:32.452+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:30:32.453+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:30:32.469+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_19722414, execution_date=20240610T000000, start_date=20240611T213031, end_date=20240611T213032
[2024-06-11T21:30:32.495+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 177 for task load_index_id_19722414 (Task failed due to SystemExit(1); 373)
[2024-06-11T21:30:32.525+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:30:32.556+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:30:32.561+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T21:31:24.218+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:31:24.317+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:31:24.337+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:31:24.338+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:31:24.442+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_19722414> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:31:24.454+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_19722414', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmpstau4_0e']
[2024-06-11T21:31:24.457+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=410) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:31:24.458+0000] {standard_task_runner.py:91} INFO - Job 188: Subtask load_index_id_19722414
[2024-06-11T21:31:24.458+0000] {standard_task_runner.py:63} INFO - Started process 411 to run task
[2024-06-11T21:31:24.572+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:31:24.782+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_19722414' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:31:24.785+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:31:24.861+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:31:24.863+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:31:24.865+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:31:24.883+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_19722414, execution_date=20240610T000000, start_date=20240611T213124, end_date=20240611T213124
[2024-06-11T21:31:24.911+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 188 for task load_index_id_19722414 (Task failed due to SystemExit(1); 411)
[2024-06-11T21:31:24.957+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:31:25.002+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:31:25.008+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T21:41:29.327+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:41:29.395+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:41:29.410+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:41:29.411+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:41:29.435+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_19722414> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:41:29.449+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_19722414', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpa2bg82ir']
[2024-06-11T21:41:29.452+0000] {standard_task_runner.py:91} INFO - Job 245: Subtask load_index_id_19722414
[2024-06-11T21:41:29.455+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=221) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:41:29.457+0000] {standard_task_runner.py:63} INFO - Started process 222 to run task
[2024-06-11T21:41:29.519+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_19722414 scheduled__2024-06-10T00:00:00+00:00 [running]> on host 8195540d7f15
[2024-06-11T21:41:29.855+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_19722414' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:41:29.856+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:41:29.908+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:41:29.909+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data.py", line 19, in load_index
    print(response.json()["info"])
          ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'info'
[2024-06-11T21:41:29.932+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_19722414, execution_date=20240610T000000, start_date=20240611T214129, end_date=20240611T214129
[2024-06-11T21:41:29.954+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 245 for task load_index_id_19722414 ('info'; 222)
[2024-06-11T21:41:29.995+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:41:30.027+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:41:30.033+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
