[2024-06-11T21:33:38.998+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:33:39.049+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703831 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:39.061+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703831 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:39.062+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:33:39.085+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_703831> on 2024-06-11 21:33:17.294204+00:00
[2024-06-11T21:33:39.094+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_703831', 'manual__2024-06-11T21:33:17.294204+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp6f3mkoru']
[2024-06-11T21:33:39.100+0000] {standard_task_runner.py:91} INFO - Job 222: Subtask load_index_id_703831
[2024-06-11T21:33:39.105+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=552) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:33:39.106+0000] {standard_task_runner.py:63} INFO - Started process 553 to run task
[2024-06-11T21:33:39.189+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_703831 manual__2024-06-11T21:33:17.294204+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:33:39.688+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_703831' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:33:17.294204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:33:17.294204+00:00'
[2024-06-11T21:33:39.690+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:33:39.783+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:33:39.784+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:33:39.785+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:33:39.805+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_703831, execution_date=20240611T213317, start_date=20240611T213339, end_date=20240611T213339
[2024-06-11T21:33:39.839+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 222 for task load_index_id_703831 (Task failed due to SystemExit(1); 553)
[2024-06-11T21:33:39.886+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:33:39.918+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:33:39.924+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
