[2024-04-25T21:14:50.232+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T21:14:50.283+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.task_2 manual__2024-04-25T21:14:42.515218+00:00 [queued]>
[2024-04-25T21:14:50.296+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.task_2 manual__2024-04-25T21:14:42.515218+00:00 [queued]>
[2024-04-25T21:14:50.297+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-04-25T21:14:50.321+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): task_2> on 2024-04-25 21:14:42.515218+00:00
[2024-04-25T21:14:50.331+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'task_2', 'manual__2024-04-25T21:14:42.515218+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/python_op.py', '--cfg-path', '/tmp/tmpmy6vanim']
[2024-04-25T21:14:50.334+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1896) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T21:14:50.336+0000] {standard_task_runner.py:91} INFO - Job 149: Subtask task_2
[2024-04-25T21:14:50.336+0000] {standard_task_runner.py:63} INFO - Started process 1897 to run task
[2024-04-25T21:14:50.404+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.task_2 manual__2024-04-25T21:14:42.515218+00:00 [running]> on host f9a12f9b65d4
[2024-04-25T21:14:50.556+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='task_2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T21:14:42.515218+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T21:14:42.515218+00:00'
[2024-04-25T21:14:50.557+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T21:14:50.575+0000] {logging_mixin.py:188} INFO - 2
[2024-04-25T21:14:55.576+0000] {logging_mixin.py:188} INFO - test
[2024-04-25T21:14:55.578+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-25T21:14:55.579+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T21:14:55.592+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=task_2, execution_date=20240425T211442, start_date=20240425T211450, end_date=20240425T211455
[2024-04-25T21:14:55.628+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-25T21:14:55.649+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T21:14:55.655+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
