[2024-06-11T21:33:43.217+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:33:43.292+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701227 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:43.311+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701227 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:43.316+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:33:43.410+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701227> on 2024-06-11 21:33:17.294204+00:00
[2024-06-11T21:33:43.424+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701227', 'manual__2024-06-11T21:33:17.294204+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp3cdctarc']
[2024-06-11T21:33:43.426+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=556) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:33:43.428+0000] {standard_task_runner.py:91} INFO - Job 224: Subtask load_index_id_701227
[2024-06-11T21:33:43.429+0000] {standard_task_runner.py:63} INFO - Started process 557 to run task
[2024-06-11T21:33:43.586+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701227 manual__2024-06-11T21:33:17.294204+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:33:44.100+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701227' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:33:17.294204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:33:17.294204+00:00'
[2024-06-11T21:33:44.142+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:33:44.316+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:33:44.318+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:33:44.320+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:33:44.356+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701227, execution_date=20240611T213317, start_date=20240611T213343, end_date=20240611T213344
[2024-06-11T21:33:44.429+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 224 for task load_index_id_701227 (Task failed due to SystemExit(1); 557)
[2024-06-11T21:33:44.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:33:44.565+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:33:44.580+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
