[2024-06-11T21:33:27.873+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:33:27.966+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_704449 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:28.010+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_704449 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:28.017+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:33:28.156+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_704449> on 2024-06-11 21:33:17.294204+00:00
[2024-06-11T21:33:28.191+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=538) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:33:28.188+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_704449', 'manual__2024-06-11T21:33:17.294204+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmpbvkmooxo']
[2024-06-11T21:33:28.195+0000] {standard_task_runner.py:63} INFO - Started process 539 to run task
[2024-06-11T21:33:28.200+0000] {standard_task_runner.py:91} INFO - Job 215: Subtask load_index_id_704449
[2024-06-11T21:33:28.389+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_704449 manual__2024-06-11T21:33:17.294204+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:33:28.697+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_704449' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:33:17.294204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:33:17.294204+00:00'
[2024-06-11T21:33:28.705+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:33:28.820+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:33:28.822+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:33:28.824+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:33:28.843+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_704449, execution_date=20240611T213317, start_date=20240611T213327, end_date=20240611T213328
[2024-06-11T21:33:28.893+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 215 for task load_index_id_704449 (Task failed due to SystemExit(1); 539)
[2024-06-11T21:33:28.941+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:33:28.981+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:33:28.989+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
