[2024-06-11T21:29:29.331+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:29:29.379+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701625 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:29:29.391+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701625 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:29:29.392+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:29:29.416+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701625> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:29:29.429+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701625', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmpwy81oaqs']
[2024-06-11T21:29:29.432+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=284) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:29:29.433+0000] {standard_task_runner.py:91} INFO - Job 144: Subtask load_index_id_701625
[2024-06-11T21:29:29.434+0000] {standard_task_runner.py:63} INFO - Started process 285 to run task
[2024-06-11T21:29:29.514+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701625 scheduled__2024-06-10T00:00:00+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:29:29.725+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701625' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:29:29.727+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:29:29.784+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:29:29.785+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:29:29.786+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:29:29.797+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701625, execution_date=20240610T000000, start_date=20240611T212929, end_date=20240611T212929
[2024-06-11T21:29:29.814+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 144 for task load_index_id_701625 (Task failed due to SystemExit(1); 285)
[2024-06-11T21:29:29.851+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:29:29.911+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:29:29.917+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T21:31:31.892+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:31:31.949+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701625 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:31:31.961+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701625 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:31:31.962+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:31:31.983+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701625> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:31:31.993+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=422) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:31:31.991+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701625', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmplzmh6a3h']
[2024-06-11T21:31:31.994+0000] {standard_task_runner.py:63} INFO - Started process 423 to run task
[2024-06-11T21:31:31.995+0000] {standard_task_runner.py:91} INFO - Job 194: Subtask load_index_id_701625
[2024-06-11T21:31:32.100+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701625 scheduled__2024-06-10T00:00:00+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:31:32.257+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701625' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:31:32.259+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:31:32.315+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:31:32.318+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:31:32.319+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:31:32.337+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701625, execution_date=20240610T000000, start_date=20240611T213131, end_date=20240611T213132
[2024-06-11T21:31:32.364+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 194 for task load_index_id_701625 (Task failed due to SystemExit(1); 423)
[2024-06-11T21:31:32.411+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:31:32.442+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:31:32.452+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T21:41:36.814+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:41:36.885+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701625 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:41:36.907+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701625 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:41:36.908+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:41:36.938+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701625> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:41:36.950+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701625', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpmhip3sx3']
[2024-06-11T21:41:36.956+0000] {standard_task_runner.py:91} INFO - Job 251: Subtask load_index_id_701625
[2024-06-11T21:41:36.958+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:41:36.960+0000] {standard_task_runner.py:63} INFO - Started process 239 to run task
[2024-06-11T21:41:37.041+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701625 scheduled__2024-06-10T00:00:00+00:00 [running]> on host 8195540d7f15
[2024-06-11T21:41:37.179+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701625' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:41:37.182+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:41:37.239+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:41:37.240+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data.py", line 19, in load_index
    print(response.json()["info"])
          ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'info'
[2024-06-11T21:41:37.262+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701625, execution_date=20240610T000000, start_date=20240611T214136, end_date=20240611T214137
[2024-06-11T21:41:37.284+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 251 for task load_index_id_701625 ('info'; 239)
[2024-06-11T21:41:37.336+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:41:37.360+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:41:37.367+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
