[2024-06-11T21:29:28.504+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:29:28.554+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703831 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:29:28.569+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703831 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:29:28.570+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:29:28.593+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_703831> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:29:28.605+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:29:28.603+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_703831', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmpjkcabmar']
[2024-06-11T21:29:28.607+0000] {standard_task_runner.py:63} INFO - Started process 283 to run task
[2024-06-11T21:29:28.607+0000] {standard_task_runner.py:91} INFO - Job 143: Subtask load_index_id_703831
[2024-06-11T21:29:28.681+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_703831 scheduled__2024-06-10T00:00:00+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:29:28.826+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_703831' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:29:28.829+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:29:28.889+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:29:28.891+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:29:28.892+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:29:28.903+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_703831, execution_date=20240610T000000, start_date=20240611T212928, end_date=20240611T212928
[2024-06-11T21:29:28.918+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 143 for task load_index_id_703831 (Task failed due to SystemExit(1); 283)
[2024-06-11T21:29:28.944+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:29:28.973+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:29:28.977+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T21:31:30.054+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:31:30.111+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703831 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:31:30.126+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703831 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:31:30.127+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:31:30.150+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_703831> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:31:30.159+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_703831', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp65d41fir']
[2024-06-11T21:31:30.161+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=420) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:31:30.163+0000] {standard_task_runner.py:91} INFO - Job 193: Subtask load_index_id_703831
[2024-06-11T21:31:30.164+0000] {standard_task_runner.py:63} INFO - Started process 421 to run task
[2024-06-11T21:31:30.239+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_703831 scheduled__2024-06-10T00:00:00+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:31:30.390+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_703831' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:31:30.392+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:31:30.450+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:31:30.451+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:31:30.452+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:31:30.462+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_703831, execution_date=20240610T000000, start_date=20240611T213130, end_date=20240611T213130
[2024-06-11T21:31:30.482+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 193 for task load_index_id_703831 (Task failed due to SystemExit(1); 421)
[2024-06-11T21:31:30.501+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:31:30.525+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:31:30.531+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-11T21:41:35.433+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:41:35.478+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703831 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:41:35.500+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703831 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:41:35.501+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:41:35.533+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_703831> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:41:35.548+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_703831', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpb_ptiiud']
[2024-06-11T21:41:35.553+0000] {standard_task_runner.py:91} INFO - Job 250: Subtask load_index_id_703831
[2024-06-11T21:41:35.556+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=236) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:41:35.559+0000] {standard_task_runner.py:63} INFO - Started process 237 to run task
[2024-06-11T21:41:35.654+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_703831 scheduled__2024-06-10T00:00:00+00:00 [running]> on host 8195540d7f15
[2024-06-11T21:41:35.856+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_703831' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:41:35.857+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:41:35.905+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:41:35.907+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data.py", line 19, in load_index
    print(response.json()["info"])
          ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'info'
[2024-06-11T21:41:35.924+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_703831, execution_date=20240610T000000, start_date=20240611T214135, end_date=20240611T214135
[2024-06-11T21:41:35.940+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 250 for task load_index_id_703831 ('info'; 237)
[2024-06-11T21:41:35.976+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:41:36.001+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:41:36.008+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
