[2024-06-11T21:47:11.227+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:47:11.294+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703039 manual__2024-06-11T21:47:06.735792+00:00 [queued]>
[2024-06-11T21:47:11.311+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_703039 manual__2024-06-11T21:47:06.735792+00:00 [queued]>
[2024-06-11T21:47:11.313+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:47:11.403+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_703039> on 2024-06-11 21:47:06.735792+00:00
[2024-06-11T21:47:11.417+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_703039', 'manual__2024-06-11T21:47:06.735792+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmphi99g330']
[2024-06-11T21:47:11.421+0000] {standard_task_runner.py:91} INFO - Job 298: Subtask load_index_id_703039
[2024-06-11T21:47:11.569+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=304) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:47:11.570+0000] {standard_task_runner.py:63} INFO - Started process 305 to run task
[2024-06-11T21:47:11.600+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_703039 manual__2024-06-11T21:47:06.735792+00:00 [running]> on host f7fd8afd804e
[2024-06-11T21:47:11.777+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_703039' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:47:06.735792+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:47:06.735792+00:00'
[2024-06-11T21:47:11.778+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:47:18.295+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:47:18.296+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:47:18.298+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:47:18.311+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_703039, execution_date=20240611T214706, start_date=20240611T214711, end_date=20240611T214718
[2024-06-11T21:47:18.330+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 298 for task load_index_id_703039 (Task failed due to SystemExit(1); 305)
[2024-06-11T21:47:18.366+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:47:18.391+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:47:18.397+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
