[2024-06-11T21:33:25.404+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:33:25.512+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_704448 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:25.546+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_704448 manual__2024-06-11T21:33:17.294204+00:00 [queued]>
[2024-06-11T21:33:25.557+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:33:25.629+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_704448> on 2024-06-11 21:33:17.294204+00:00
[2024-06-11T21:33:25.655+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_704448', 'manual__2024-06-11T21:33:17.294204+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmp9ms75q0x']
[2024-06-11T21:33:25.658+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=536) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:33:25.660+0000] {standard_task_runner.py:91} INFO - Job 214: Subtask load_index_id_704448
[2024-06-11T21:33:25.660+0000] {standard_task_runner.py:63} INFO - Started process 537 to run task
[2024-06-11T21:33:25.905+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_704448 manual__2024-06-11T21:33:17.294204+00:00 [running]> on host e6f094d2943c
[2024-06-11T21:33:26.124+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_704448' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:33:17.294204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:33:17.294204+00:00'
[2024-06-11T21:33:26.125+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:33:26.178+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:33:26.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:33:26.180+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:33:26.193+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_704448, execution_date=20240611T213317, start_date=20240611T213325, end_date=20240611T213326
[2024-06-11T21:33:26.216+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 214 for task load_index_id_704448 (Task failed due to SystemExit(1); 537)
[2024-06-11T21:33:26.253+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:33:26.278+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:33:26.283+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
