[2024-04-27T19:27:14.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T19:27:14.332+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_2979005 manual__2024-04-27T19:26:59.032752+00:00 [queued]>
[2024-04-27T19:27:14.344+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_2979005 manual__2024-04-27T19:26:59.032752+00:00 [queued]>
[2024-04-27T19:27:14.345+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-04-27T19:27:14.369+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_2979005> on 2024-04-27 19:26:59.032752+00:00
[2024-04-27T19:27:14.378+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=932) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-27T19:27:14.381+0000] {standard_task_runner.py:63} INFO - Started process 933 to run task
[2024-04-27T19:27:14.377+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_2979005', 'manual__2024-04-27T19:26:59.032752+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/python_op.py', '--cfg-path', '/tmp/tmp57hn2lgg']
[2024-04-27T19:27:14.382+0000] {standard_task_runner.py:91} INFO - Job 212: Subtask load_index_id_2979005
[2024-04-27T19:27:14.456+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_2979005 manual__2024-04-27T19:26:59.032752+00:00 [running]> on host d933ead87eb5
[2024-04-27T19:27:14.656+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_2979005' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T19:26:59.032752+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T19:26:59.032752+00:00'
[2024-04-27T19:27:14.658+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T19:27:23.191+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-27T19:27:23.194+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T19:27:23.212+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=load_data_mb, task_id=load_index_id_2979005, execution_date=20240427T192659, start_date=20240427T192714, end_date=20240427T192723
[2024-04-27T19:27:23.259+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-27T19:27:23.301+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T19:27:23.307+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
